export enum JOUR_CHOME_PAQUE {
    ASSOMPTION   = 'JC_ASSOM',
    PAQUES   = 'JC_PAQUES',
    LUNDI_PAQUES   = 'JC_LPAQUES',
    ASCENSION   = 'JC_ASCEN',
    PENTECOTE   = 'JC_PENTE',
    LUNDI_PENTECOTE   = 'JC_LPENTE',
    VENDREDI_SAINT   = 'JC_VSAIN',
}
